# Colors (Alabaster Dark)
colors:
  name: Alabaster (dark)
  author: tonsky
  primary:
    background: "#000003"
    foreground: "#ffffff"
  cursor:
    text: "#000000"
    cursor: "#4ac9e2"
  normal:
    black: "#000000"
    red: "#ff0000"
    green: "#00ff00"
    yellow: "#e9bf57"
    blue: "#0000ff"
    magenta: "#915caf"
    cyan: "#4ac9e2"
    white: "#ffffff"
  bright:
    black: "#777777"
    red: "#f36868"
    green: "#88db3f"
    yellow: "#f0bf7a"
    blue: "#6f8fdb"
    magenta: "#e987e9"
    cyan: "#4ac9e2"
    white: "#FFFFFF"
